### ISSUE TITLE
Problem error when render preview !

### ISSUE THREAD

**Issue by Noobknight** [MiguelCatalan/MaterialSearchView#16]
I'm use theme 
```
<style name="ShortStoryTheme" parent="AppBaseTheme">
        <item name="android:textColorPrimary">@android:color/white</item>
        <item name="drawerArrowStyle">@style/DrawerArrowStyle</item>
        <item name="android:windowTranslucentStatus" tools:targetApi="19">true</item>
        <item name="android:windowContentOverlay">@null</item>
        <item name="windowActionBar">false</item>
        <!-- Toolbar Theme / Apply white arrow -->
        <item name="colorControlNormal">@android:color/white</item>
        <item name="actionBarTheme">@style/ShortStory_AppTheme.ActionBarTheme</item>
        <item name="android:windowActionBarOverlay" tools:targetApi="21">true</item>
        <item name="android:background">@android:color/transparent</item>
        <item name="windowNoTitle">true</item>

        <item name="android:windowBackground">@color/theme_background</item>
        <item name="actionMenuTextColor">@color/theme_icons</item>
        <item name="android:textColorSecondary">@color/theme_icons</item>

        <!-- Material Theme -->
        <item name="colorPrimary">@color/nliveo_red_colorPrimary</item>
        <item name="colorPrimaryDark">@color/nliveo_red_colorPrimaryDark</item>
        <item name="colorAccent">@color/nliveo_green_colorAccent</item>
        <item name="android:statusBarColor" tools:targetApi="21">@color/statusBarColor</item>
        <item name="android:navigationBarColor" tools:targetApi="21">@color/navigationBarColor
        </item>
        <item name="android:windowDrawsSystemBarBackgrounds" tools:targetApi="21">true</item>
    </style>
```
And occur error when preview.
```
java.lang.NullPointerException
	at com.miguelcatalan.materialsearchview.MaterialSearchView.setBackground(MaterialSearchView.java:297)
	at android.view.View.<init>(View.java:4328)
	at android.view.ViewGroup.<init>(ViewGroup.java:573)
	at android.widget.FrameLayout.<init>(FrameLayout.java:97)
	at android.widget.FrameLayout.<init>(FrameLayout.java:92)
	at android.widget.FrameLayout.<init>(FrameLayout.java:88)
	at com.miguelcatalan.materialsearchview.MaterialSearchView.<init>(MaterialSearchView.java:87)
	at com.miguelcatalan.materialsearchview.MaterialSearchView.<init>(MaterialSearchView.java:83)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:458)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:170)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:103)
	at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadView(LayoutlibCallbackImpl.java:190)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:218)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:145)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:835)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:811)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:838)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:811)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:394)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:223)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:426)
	at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:350)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:510)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:498)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:888)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:498)
	at com.android.tools.idea.rendering.RenderTask.access$600(RenderTask.java:72)
	at com.android.tools.idea.rendering.RenderTask$3.call(RenderTask.java:610)
	at com.android.tools.idea.rendering.RenderTask$3.call(RenderTask.java:607)
	at com.android.tools.idea.rendering.RenderService.runRenderAction(RenderService.java:366)
	at com.android.tools.idea.rendering.RenderTask.render(RenderTask.java:607)
	at com.android.tools.idea.rendering.RenderTask.render(RenderTask.java:629)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager.doRender(AndroidLayoutPreviewToolWindowManager.java:652)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager.access$1700(AndroidLayoutPreviewToolWindowManager.java:80)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager$7$1.run(AndroidLayoutPreviewToolWindowManager.java:594)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:152)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:137)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager$7.run(AndroidLayoutPreviewToolWindowManager.java:589)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:320)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:310)
	at com.intellij.util.ui.update.MergingUpdateQueue$2.run(MergingUpdateQueue.java:254)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:269)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:227)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:217)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:351)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by MiguelCatalan** [comment]
Can you show me your layout file?

**Comment by Noobknight** [comment]
I test use code xml in sample you provide...!! But don't work.
code here
```
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/container"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <!-- Irrelevant stuff -->

    <!-- Must be last for right layering display -->
    <FrameLayout
        android:id="@+id/toolbar_container"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

        <android.support.v7.widget.Toolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            android:background="@color/theme_primary" />

        <com.miguelcatalan.materialsearchview.MaterialSearchView
            android:id="@+id/search_view"
            android:layout_width="match_parent"
            android:layout_height="wrap_content" />
    </FrameLayout>

</FrameLayout>
```

**Comment by Noobknight** [comment]
Library occur two error 
+ setBackground when use theme of me
+ isVoiceAvailable when use theme in sample provide
Sorry i speak English not good !

**Comment by MiguelCatalan** [comment]
If I get it right, you are saying the AS preview report that error? or the error occurs in run time?

**Comment by Devofure** [comment]
Hi, I having the same error, it is the Android Studio preview that shows the error.
![image](https://cloud.githubusercontent.com/assets/7500992/11023465/e6d5ca28-8679-11e5-8f47-f3f569b1b91b.png)
