### ISSUE TITLE
My app happen with some error it throw this exception, could you tell me how?

### ISSUE THREAD

**Issue by hoangtuanhedspi** [MiguelCatalan/MaterialSearchView#170]
java.lang.IllegalStateException: 
  at android.view.RenderNode.addAnimator(RenderNode.java:786)
  at android.view.RenderNodeAnimator.setTarget(RenderNodeAnimator.java:297)
  at android.view.RenderNodeAnimator.setTarget(RenderNodeAnimator.java:279)
  at android.animation.RevealAnimator.<init>(RevealAnimator.java:37)
  at android.view.ViewAnimationUtils.createCircularReveal(ViewAnimationUtils.java:71)
  at com.miguelcatalan.materialsearchview.utils.AnimationUtil.reveal(AnimationUtil.java:86)
  at com.miguelcatalan.materialsearchview.MaterialSearchView.setVisibleWithAnimation(MaterialSearchView.java:553)
  at com.miguelcatalan.materialsearchview.MaterialSearchView.showSearch(MaterialSearchView.java:519)
  at com.miguelcatalan.materialsearchview.MaterialSearchView.showSearch(MaterialSearchView.java:501)

**Comment by tmeinhart** [comment]
Hi, 
i got the same error in my app. Did you have any solution on this why this happens?
