### ISSUE TITLE
Inflate exception when override background in app theme

### ISSUE THREAD

**Issue by SiiTP** [MiguelCatalan/MaterialSearchView#204]
Caused by: android.view.InflateException: Binary XML file line #39: Error inflating class com.miguelcatalan.materialsearchview.MaterialSearchView
at android.view.LayoutInflater.createView(LayoutInflater.java:620)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
at android.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:276)
at android.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:261)
at com.myapp.activities.DrawerActivity.onCreate(DrawerActivity.kt:52)
at android.app.Activity.performCreate(Activity.java:5133)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2230)

I got this exception when add
`       
 <item name="android:background">@color/green</item>
`
in my **styles.xml**. Android 4.3.

**Comment by Bertkiing** [comment]
I also meet the question... please help me...
