### ISSUE TITLE
Android 9 - API version 28 P: IllegalArgumentException  parameter previouslyFocusedRect specified as non-null is null: method 

### ISSUE THREAD

**Issue by pajuscz** [MiguelCatalan/MaterialSearchView#218]
This is happening only If i try to use `MaterialSearchView` under Android 9 API Version 28 P. For older version it works.
I am using `MaterialSearchView` in the way that I add it into my layout file. The app won't load and crashes instantly when trying to load the `MaterialSearchView`.

Full stack trace
```
E/AndroidRuntime: FATAL EXCEPTION: main
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter previouslyFocusedRect
        at copySearchView.MaterialSearchView.requestFocus(Unknown Source:2)
        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3282)
        at android.view.ViewGroup.requestFocus(ViewGroup.java:3231)
        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3282)
        at android.view.ViewGroup.requestFocus(ViewGroup.java:3236)
        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3282)
        at android.view.ViewGroup.requestFocus(ViewGroup.java:3231)
        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3282)
        at android.view.ViewGroup.requestFocus(ViewGroup.java:3231)
        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3282)
        at android.view.ViewGroup.requestFocus(ViewGroup.java:3231)
        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3282)
        at android.view.ViewGroup.requestFocus(ViewGroup.java:3231)
        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3282)
        at android.view.ViewGroup.requestFocus(ViewGroup.java:3236)
        at android.view.View.requestFocus(View.java:11487)
        at android.view.View.restoreDefaultFocus(View.java:11466)
        at android.view.ViewGroup.restoreDefaultFocus(ViewGroup.java:3298)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2403)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:696)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
I am using Kotlin if that helps.

**Comment by sahillikeminds** [comment]
Are you able to solve this error?
