### ISSUE TITLE
Open search when activity opens

### ISSUE THREAD

**Issue by Anushree278** [MiguelCatalan/MaterialSearchView#234]
can we open search edittext field whenever activity opens

**Comment by n-droidev** [comment]
Just add `materialSearchView.showSearch();` to your `onCreate` method.

**Comment by onexoff** [comment]
@techwizard1  it doesn't work with me 

```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.miguelcatalan.materialsearchview.MaterialSearchView.showSearch()' on a null object reference
        at com.ova.studio.anime.wallpaper.ui.InputTypeActivity.onCreate(InputTypeActivity.java:31)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2905)
```
