### ISSUE TITLE
 java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.toLowerCase()

### ISSUE THREAD

**Issue by Spiderbezno** [MiguelCatalan/MaterialSearchView#74]
I sen d and array os string of 21 elements and mthe las could be null

An exception occured during performFiltering()!
                                                                            java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.toLowerCase()' on a null object reference
                                                                                at com.miguelcatalan.materialsearchview.SearchAdapter$1.performFiltering(SearchAdapter.java:57)
                                                                                at android.widget.Filter$RequestHandler.handleMessage(Filter.java:234)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:135)
                                                                                at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by ampatron** [comment]
Same issue here but when I force stop the app and clear the data, it already works. This should not be the case because we cannot tell the user to try to clear their data and force close the app every time they encounter this. I can replicate this by simply trying out search first then reinstalling the app.

**Comment by 0v4tsug** [comment]
i had the same issue, and the problem was an array filled with null values. Check that your array with suggestions dont contain any null value.

**Comment by lisumac** [comment]
Attempt to invoke virtual method 'java.lang.String java.lang.String.toLowerCase()' on a null object reference

i am also getting the same issue
